### ISSUE TITLE
[Release] duplicate-detection v0.1.0

### ISSUE THREAD

**Issue by PeterWang-dev** [PeterWang-dev/3121005231#15]
# TASKS FOR RELEASE

- [ ] Merge `dev` into `main`

# CHANGE LOG

## Features

- [ ] #3 Processor Library
- [ ] #4 Pre-processor  Library
- [ ] #2 Frontend Command-Line Interface
